name: Keep Render Awake (6AM - 12PM ICT)

on:
  schedule:
    # Đổi thành 10 phút để bù trừ độ trễ (delay queue) của Github
    - cron: '*/10 * * * *'
  
  workflow_dispatch: 

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        # Thêm -L (follow redirect) và -A (fake User-Agent)
        run: curl -s -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" https://vinfast-backend-57wa.onrender.com > /dev/null
